version: "3.3"

services:
  django:
    container_name: django
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/usr/src/django
    command: >
      sh -c "python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_TIME_ZONE: ${DJANGO_TIME_ZONE}
      DJANGO_LANGUAGE_CODE: ${DJANGO_LANGUAGE_CODE}
      DJANGO_NEXTJS_URL: ${DJANGO_NEXTJS_URL}
      TZ: "Asia/Seoul"
    restart: always
    networks:
      - server-network

  fastapi:
    container_name: fastapi
    build:
      context: ./ai
      dockerfile: Dockerfile
    volumes:
      - ./ai:/usr/src/fastapi
    restart: always
    ports:
      - "9000:9000"
    environment:
      FASTAPI_API_DOMAIN: ${FASTAPI_API_DOMAIN}
      FASTAPI_API_URL: ${FASTAPI_API_URL}
      FASTAPI_OPENAI_KEY: ${FASTAPI_OPENAI_KEY}
      TZ: "Asia/Seoul"
    depends_on:
      - springboot
    networks:
      - server-network

  nextjs:
    container_name: nextjs
    restart: "always"
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_ENV_API_DOMAIN: ${NEXT_PUBLIC_ENV_API_DOMAIN}
        NEXT_PUBLIC_ENV_API_URL: ${NEXT_PUBLIC_ENV_API_URL}
        NEXT_PUBLIC_ENV_DOMAIN: ${NEXT_PUBLIC_ENV_DOMAIN}
    environment:
      TZ: "Asia/Seoul"
    networks:
      - server-network

  nginx:
    container_name: nginx
    restart: "always"
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
      # - "80:80"
      # - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      # certbot
      - /etc/letsencrypt:/etc/letsencrypt
      # letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
      - ./nginx/sites.conf:/etc/nginx/conf.d/sites.conf
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled
    environment:
      NGINX_HOST: ${NGINX_HOST}
      NGINX_PORT: ${NGINX_PORT}
      NGINX_SERVER_NAME: ${NGINX_SERVER_NAME}
      NGINX_SSL_CERTIFICATE: ${NGINX_SSL_CERTIFICATE}
      NGINX_SSL_CERTIFICATE_KEY: ${NGINX_SSL_CERTIFICATE_KEY}
      NGINX_SSL_TRUSTED_CERTIFICATE: ${NGINX_SSL_TRUSTED_CERTIFICATE}
      TZ: "Asia/Seoul"
    depends_on:
      - nextjs
      - springboot
      - mysqldb
      - fastapi
    networks:
      - server-network

networks:
  server-network:
    driver: bridge
# certbot docker container
# docker run -it --rm --name certbot \
#             -v "/etc/letsencrypt:/etc/letsencrypt" \
#             -v "/var/lib/letsencrypt:/var/lib/letsencrypt" \
#             certbot/certbot \
#             certonly \
#             --webroot \
#             -w /var/lib/letsencrypt \
#             -d www.seniorplus.site \
#             --agree-tos
