version: "3.3"

services:
  nextjs:
    container_name: nextjs
    restart: "always"
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_ENV_API_DOMAIN: ${NEXT_PUBLIC_ENV_API_DOMAIN}
        NEXT_PUBLIC_ENV_API_URL: ${NEXT_PUBLIC_ENV_API_URL}
        NEXT_PUBLIC_ENV_DOMAIN: ${NEXT_PUBLIC_ENV_DOMAIN}
        NEXT_PUBLIC_ENV_JWT_SECRET_KEY: ${NEXT_PUBLIC_ENV_JWT_SECRET_KEY}
    environment:
      TZ: "Asia/Seoul"
    ports:
      - "3000:3000"
    networks:
      - server-network

networks:
  server-network:
    driver: bridge
